import type { Metadata } from "next";
import { Comfortaa } from 'next/font/google'
import { Gabarito } from 'next/font/google'

const comfortaa = Comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

const gabarito = Gabarito({
  subsets: ['latin'],
  display: 'swap',
})
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={[comfortaa.className, gabarito.className].join(" ")}>{children}</body>
    </html>
  );
}
